In [1]:
import numpy as np

In [6]:
n = np.arange(2,41,7)
n

array([ 2,  9, 16, 23, 30, 37])

In [9]:
p = np.array([[2,5,8,9],[5,9,4,2],[8,4,6,2]])
p

array([[2, 5, 8, 9],
       [5, 9, 4, 2],
       [8, 4, 6, 2]])

In [10]:
p[1:3,1:3]

array([[9, 4],
       [4, 6]])

In [12]:
r = np.arange(2,20,2)
r

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
r1 = r+1
r1

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
r2 = np.add(r1,r)
r2

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37])

In [21]:
r3 = np.multiply(r,r1)
r3

array([  6,  20,  42,  72, 110, 156, 210, 272, 342])

In [24]:
r4 = np.divide (r3,r)
r4

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])