In [3]:
import numpy as np

In [3]:
a10 = np.arange(10)
a10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
s = a10+5
s


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a2d = np.array([[1,2],[3,4],[5,6]])
a2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
n = np.array((1,2,3))
n

array([1, 2, 3])

In [11]:
s = a2d+5
s

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
# z = n*s
#Dimension error

In [15]:
#Stacking and Splitting
p = np.array([[1,2],[3,4],[5,6]])
p

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
s =np.array((2,3))
z = np.array((4,5))

In [19]:
y = np.array([[7,8], [9,10],[11,12]])
stack = np.hstack((p,y))
stack

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [20]:
# vertical stacking, vstack()
v_stack = np.vstack((p,y))
v_stack

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
d_stack = np.dstack((p,y))
d_stack

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [43]:
r = np.array(([1,2],[3,4],[5,6],[7,8]))
s = np.array(([7,5],[3,9]))

# d_stk = np.dstack((r,s))
# d_stk

In [28]:
#splitting

a = np.arange(9)
b = np.split(a,3)
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [51]:
c = r[1:5,1:4]
c

array([[4],
       [6],
       [8]])

In [33]:
ary = np.array((5,10,11,13,15,20,25))
ary

array([ 5, 10, 11, 13, 15, 20, 25])

In [34]:
condt = ary%5==0
print(ary[condt])

[ 5 10 15 20 25]


In [35]:
condt


array([ True,  True, False, False,  True,  True,  True])

In [40]:
#create an array of first 10 multiples of 6
#slice array of more than 25

arr = np.arange(6,61,6)
cond = arr>25
sliced_arr = arr[cond]
sliced_arr

array([30, 36, 42, 48, 54, 60])

In [41]:
#slicing 2D arrays
a = np.array([[1,2,3],[4,5,6],[8,9,10]])

In [42]:
#slicing [:] [[,]], [condition]