In [1]:
import numpy as np

In [2]:
#revision dstack()

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[5, 6],
       [7, 8]])

In [7]:
d_stack = np.dstack((a,b))
d_stack

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [8]:
#Fancy Indexing

In [9]:
a2d=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
a2d.shape

(6, 5)

In [11]:
out = [1,4,5]
a2d[out]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
#indexing with condition
condition = a2d%5==0
a2d[condition]

array([ 5, 10, 15, 20, 25, 30])

In [25]:
#create random array of 5x6
#condition greater than 30 and less than 50
a2d = np.random.randint(20,70,30).reshape(5,6)
a2d

array([[55, 63, 34, 47, 62, 55],
       [55, 43, 65, 63, 45, 25],
       [51, 29, 63, 61, 20, 62],
       [31, 31, 35, 42, 24, 34],
       [53, 45, 44, 27, 33, 28]])

In [26]:
condn = (a2d > 30) & (a2d < 50)
a2d[condn]

array([34, 47, 43, 45, 31, 31, 35, 42, 34, 45, 44, 33])

In [27]:
row = [1]
cols = [1,3,4]
a2d[row,cols]

array([43, 63, 45])

In [28]:
row = [(1,3),(2,4)]
cols = [2,4]
a2d[row,cols]

array([[65, 24],
       [63, 33]])

In [30]:
#reshaping arrays

ax = np.random.randint(1,68,30).reshape(5,6)
ax

array([[12, 10, 62, 66, 56, 10],
       [14, 26, 47, 13, 46, 25],
       [44, 36, 43,  4, 66, 45],
       [11, 45,  6,  5, 14,  9],
       [48,  9, 39, 45, 17, 66]])

In [33]:
ax.reshape(6,5)

array([[12, 10, 62, 66, 56],
       [10, 14, 26, 47, 13],
       [46, 25, 44, 36, 43],
       [ 4, 66, 45, 11, 45],
       [ 6,  5, 14,  9, 48],
       [ 9, 39, 45, 17, 66]])

In [ ]:
#flatten()
#ravel()
#reshape()


In [35]:
aray = np.random.randint(1,80,20).reshape(5,4)
aray

array([[17, 42, 30, 31],
       [70, 15, 49, 47],
       [65, 58, 60, 20],
       [56, 15, 51, 51],
       [ 9, 10, 50, 52]])

In [42]:
aray.flatten()

array([17, 42, 30, 31, 70, 15, 49, 47, 65, 58, 60, 20, 56, 15, 51, 51,  9,
       10, 50, 52])

In [44]:
aray.ravel()

array([17, 42, 30, 31, 70, 15, 49, 47, 65, 58, 60, 20, 56, 15, 51, 51,  9,
       10, 50, 52])

In [45]:
#different between ravel() and flatten()
#what c and f in ravel()