In [2]:
import numpy as np

In [17]:
#we deal with array not list 

#diff between array and list
#array is a collection of elements of the same type whereas a list can have different types of elements
#array is faster than list
#array is more memory efficient than list
#array supports vectorized operations while list does not


In [3]:
#creating array
#using arange() function
x=np.arange(10)

In [7]:
x=np.arange(5,50)
y=np.arange(5,50,5)

In [8]:
#creating array with aray method 
a=np.array([1])
a

array([1])

In [9]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [10]:
#creating array with other datatypes 
#using list tuples string and set 
#using list 
list_x=[1,2,3,4,5]
ar=np.array(list_x)
ar

array([1, 2, 3, 4, 5])

In [11]:
#using tuples 
tuple_x=(1,2,3,4,5)
ary=np.array(tuple_x)

In [12]:
#using list with different datatypes to create array
list_x=[1,2,3,4,5.0,"a","b"]
np.array(list_x)
#converts everything into unicode characters 


array(['1', '2', '3', '4', '5.0', 'a', 'b'], dtype='<U32')

In [13]:
#using set to create arrayb 
set_x={"a","e","i","o","u"}
ar_set=np.array(set_x)
ar_set

array({'u', 'o', 'i', 'e', 'a'}, dtype=object)

In [14]:
# ..............accessing elements of array.....................
#indexing and ordering is possible as that of list 
x[0]
x[-1]


49

In [15]:
x=np.arange(5,51,5)
x

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [16]:
len(x)




10

In [17]:
#updating elements of array
x[0]=100
x

array([100,  10,  15,  20,  25,  30,  35,  40,  45,  50])

In [18]:
#creating 2d array
#difference between 2d array and 1d array is that 2d array has rows and columns
#2d array is also called as matrix
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#it has two methods 
#shape 
#ndim
#dtype
a2d.shape

(3, 3)

In [32]:
a2d.ndim

2

In [19]:
a2d.dtype

dtype('int32')

In [20]:
#creating a 5*6 array 
ar56=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30]])
ar56.shape

(5, 6)

In [21]:
#slicing of array 
#slicing is same as that of list
#for single array
#[start:stop:step]
#[default:end:step]
#[default:default:step]
x[:5]

array([100,  10,  15,  20,  25])

In [22]:
x[1:5]

array([10, 15, 20, 25])

In [23]:
#for 2d array 
#doing same process in both rows and columns
ar56[1,1:5]

array([ 8,  9, 10, 11])

In [24]:
ar56[1:4,1:5] #getting element 1 to 4th rows from both columns 1 to 5

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23]])

In [25]:
#basic operation with array 
#addition
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
z=np.add(x,y)
z # uses the concepts of matrix addition 

array([ 7,  9, 11, 13, 15])

In [26]:
#multiplication
z1=np.multiply(x,y)
z1#same concepts of matrix multiplication

array([ 6, 14, 24, 36, 50])

In [27]:
z2=np.divide(x,y)
z2#same concepts of matrix division

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [28]:
z3=np.exp(x)
z3

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [29]:
z4=np.log(x)
z4

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [30]:
z5=np.sin(x)
z5

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [57]:
#assignment find another 6 mrthods not done in class 

In [31]:
#sum mean max min std var
x.sum()

15

In [32]:
x.mean()

3.0

In [33]:
x.std()

1.4142135623730951

In [34]:
x.var()

2.0

In [35]:
x.max()

5

In [36]:
#...............broadcasting.....................


In [37]:
#for one dimensional array  
a1d=np.arange(6)
a1d

array([0, 1, 2, 3, 4, 5])

In [38]:
y=a1d+5
y

array([ 5,  6,  7,  8,  9, 10])

In [39]:
z=a1d*5
z

array([ 0,  5, 10, 15, 20, 25])

In [40]:
z1=a1d/5
z1

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])