In [1]:
import numpy as np


In [11]:
b = np.array([range(1,4), range(5,8), range(10,13)])
b


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11, 12]])

In [12]:
a = np.array([range(9,12), range(3,6), range(7,10)])
a

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 7,  8,  9]])

In [14]:
rng = []
k = 5
for x in range(10):
    rng.append(range(x,k))
    k+=1
rng

[range(0, 5),
 range(1, 6),
 range(2, 7),
 range(3, 8),
 range(4, 9),
 range(5, 10),
 range(6, 11),
 range(7, 12),
 range(8, 13),
 range(9, 14)]

In [20]:
a = np.array(rng)
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [21]:
a.shape

(10, 5)

In [24]:
np.split(a,5)

[array([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5]]),
 array([[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]),
 array([[4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]]),
 array([[ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11]]),
 array([[ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]])]

In [27]:
np.array_split(a,3)

[array([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]),
 array([[ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]]),
 array([[ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]])]

In [31]:
ary = np.array([range(1,5), range(2,6), range(3,7)])
ary

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [32]:
ary.shape

(3, 4)

In [33]:
np.array_split(ary,5)

[array([[1, 2, 3, 4]]),
 array([[2, 3, 4, 5]]),
 array([[3, 4, 5, 6]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [34]:
#dsplitting

np.dsplit(ary)

TypeError: dsplit() missing 1 required positional argument: 'indices_or_sections'

In [36]:
d3 = np.array([rng])
d3

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]]])

In [37]:
d3.shape

(1, 10, 5)

In [38]:
np.dsplit(d3,3)

ValueError: array split does not result in an equal division

<h1>Functions</h1>

In [39]:
#function : set or piece or block of code that does a specific task
#methods()


In [40]:
#arguments and parameters

In [42]:
def volume(l,b,h):
    return l*b*h

volume(2,4,5)

40

In [43]:
# *args
# **kwargs

In [ ]:
# sum(x,y):
# sum(*x):
# sum(x,**x):


In [ ]:
#with argument with return value
#with argument without return value
#without argument with return value
#without argument without return value

In [3]:
#with argument with return value
def example1(x,y,z):
    sum = x+y+z
    return sum

a = int(input("Enter your number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

z  = example1(a,b,c)
print("The values is: ", z)
#without

The values is:  20


In [7]:
#with argument without return value
def example2(a,b,c):
    print(a+b+c)

a = int(input("Enter your number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

example2(a,b,c)

20


In [10]:
# *args

def exampleA(*values):
    sum=0
    for x in values:
        sum = sum+x
    return sum

exampleA(1,5,8,7,6)

27

In [15]:
# **kwargs

def ex(name, address, *marks):
    sum = 0
    print ("name of person", name)
    print ("address", address)
    for x in marks:
        sum = sum+x
    print("marks", sum)
    
ex("Snake", "Australia", 5,8,7,9,7)

name of person Snake
address Australia
marks 36
