In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [3]:
iris=sns.load_dataset('iris')

In [4]:
iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [5]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
encode={'setosa':0,'versicolor':1,'virginica':2}

In [7]:
iris['species']=iris['species'].map(encode)

In [8]:
X=iris.drop('species',axis=1)
y=iris['species']

In [9]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)

<h1>Logistic regression</h1>

In [10]:
iris_lr=LogisticRegression()

In [11]:
iris_lr.fit(X_train, y_train)

LogisticRegression()

In [12]:
lr_pred=iris_lr.predict(X_test)
lr_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

<h1>SVM</h1>

In [13]:
from sklearn.svm import SVC

In [14]:
svc=SVC()

In [15]:
svc.fit(X_train,y_train)

SVC()

In [16]:
svc_pred=svc.predict(X_test)
svc_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [17]:
# Training with Decision Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
df = DecisionTreeClassifier()

In [22]:
df.fit(X_train, y_train)

DecisionTreeClassifier()

In [23]:
df_pred = df.predict(X_test)
df_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [24]:
# Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [27]:
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [28]:
rf_pred = rf.predict(X_test)

In [29]:
rf_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [30]:
# Training with KNeighbors

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn = KNeighborsClassifier(n_neighbors=3)

In [34]:
# Training model with knn

In [35]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [36]:
knn_pred = knn.predict(X_test)

In [37]:
knn_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)