In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression

#supervised learning
-classification
-prediction:numerical values: single variable,multiple variable,multiple variable with categorical data

In [2]:
data=pd.read_csv(r'tips_data_ready_to_use.csv')
data

Unnamed: 0  total_bill       tip  sex  smoker       day  time  size
0             0    0.291579  0.001111  0.0     0.0  0.666667   0.0   0.2
1             1    0.152283  0.073333  1.0     0.0  0.666667   0.0   0.4
2             2    0.375786  0.277778  1.0     0.0  0.666667   0.0   0.4
3             3    0.431713  0.256667  1.0     0.0  0.666667   0.0   0.2
4             4    0.450775  0.290000  0.0     0.0  0.666667   0.0   0.6
..          ...         ...       ...  ...     ...       ...   ...   ...
239         239    0.543779  0.546667  1.0     0.0  0.333333   0.0   0.4
240         240    0.505027  0.111111  0.0     1.0  0.333333   0.0   0.2
241         241    0.410557  0.111111  1.0     1.0  0.333333   0.0   0.2
242         242    0.308965  0.083333  1.0     0.0  0.333333   0.0   0.2
243         243    0.329074  0.222222  0.0     0.0  1.000000   0.0   0.2

[244 rows x 8 columns]

In [3]:
#linear regression(labeled)
X=data.drop('tip',axis=1)
X

Unnamed: 0  total_bill  sex  smoker       day  time  size
0             0    0.291579  0.0     0.0  0.666667   0.0   0.2
1             1    0.152283  1.0     0.0  0.666667   0.0   0.4
2             2    0.375786  1.0     0.0  0.666667   0.0   0.4
3             3    0.431713  1.0     0.0  0.666667   0.0   0.2
4             4    0.450775  0.0     0.0  0.666667   0.0   0.6
..          ...         ...  ...     ...       ...   ...   ...
239         239    0.543779  1.0     0.0  0.333333   0.0   0.4
240         240    0.505027  0.0     1.0  0.333333   0.0   0.2
241         241    0.410557  1.0     1.0  0.333333   0.0   0.2
242         242    0.308965  1.0     0.0  0.333333   0.0   0.2
243         243    0.329074  0.0     0.0  1.000000   0.0   0.2

[244 rows x 7 columns]

In [4]:
y=data['tip']

In [5]:
#split train and test data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
#create an instance of linearregression
tips_linear=LinearRegression()

In [7]:
#train the model
tips_linear.fit(X_test,y_test)

LinearRegression()

In [8]:
y_prediction=tips_linear.predict(X_test)

In [9]:
y_prediction

array([ 2.02496192e-01,  1.06152204e-01,  2.01984656e-01,  2.55359409e-01,
        1.51583205e-01,  1.87868829e-01,  3.06466643e-01,  1.05591452e-01,
        1.68250733e-01,  1.96061448e-01,  1.84674759e-01, -1.47247829e-02,
        9.02094326e-02,  1.51069261e-01,  9.76313912e-02,  1.64971034e-01,
        2.05178174e-01,  2.37002251e-01,  1.54958965e-01,  4.07609019e-01,
        2.32508009e-01,  2.20905581e-01,  1.90658191e-01,  8.99344252e-02,
        2.33335447e-01,  8.69250810e-02,  1.19767239e-01,  3.28037116e-01,
        1.12896959e-01,  4.64524910e-01,  3.62649686e-01,  4.51261544e-02,
        1.93959770e-01,  2.69973971e-01,  2.05586914e-01,  2.45093444e-01,
        1.50203395e-01,  4.85376212e-01,  1.04123276e-01,  1.90382745e-01,
        7.40584070e-02,  1.25521630e-01,  2.05394821e-01,  1.36217284e-01,
        1.11895364e-01,  8.89080709e-02,  1.16960811e-01,  1.89078392e-01,
       -3.97581050e-04])

In [10]:
#using real world data
new_data=pd.DataFrame({'Unnamed: 0':[243],'total_bill':[50],'sex':[2],'smoker':[3],'day':[4],'time':[5],'size':[2]})

In [11]:
new_predict=tips_linear.predict(new_data)
new_predict

array([25.69214548])

In [12]:
flights = sns.load_dataset('flights')
flights

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [13]:
df = pd.DataFrame(flights.groupby('year')['passengers'].sum())
df.reset_index()
df

passengers
year            
1949        1520
1950        1676
1951        2042
1952        2364
1953        2700
1954        2867
1955        3408
1956        3939
1957        4421
1958        4572
1959        5140
1960        5714

In [14]:
df.columns

Index(['passengers'], dtype='object')

In [15]:
# predict the passenger year wise (assignment)

In [16]:
# Categorical values
tips=sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
# One hot encoding
tips_one_hot=pd.get_dummies(tips)
tips_one_hot

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2     False        True       False       True   
1         10.34  1.66     3      True       False       False       True   
2         21.01  3.50     3      True       False       False       True   
3         23.68  3.31     2      True       False       False       True   
4         24.59  3.61     4     False        True       False       True   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3      True       False       False       True   
240       27.18  2.00     2     False        True        True      False   
241       22.67  2.00     2      True       False        True      False   
242       17.82  1.75     2      True       False       False       True   
243       18.78  3.00     2     False        True       False       True   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0       False    False    False     True       False         True  
1       False    False    False     True       False         True  
2       False    False    False     True       False         True  
3       False    False    False     True       False         True  
4       False    False    False     True       False         True  
..        ...      ...      ...      ...         ...          ...  
239     False    False     True    False       False         True  
240     False    False     True    False       False         True  
241     False    False     True    False       False         True  
242     False    False     True    False       False         True  
243      True    False    False    False       False         True  

[244 rows x 13 columns]

In [18]:
# X and Y separate

X=tips_one_hot.drop('tip',axis=1)
y=tips_one_hot['tip']

In [19]:
X

total_bill  size  sex_Male  sex_Female  smoker_Yes  smoker_No  day_Thur  \
0         16.99     2     False        True       False       True     False   
1         10.34     3      True       False       False       True     False   
2         21.01     3      True       False       False       True     False   
3         23.68     2      True       False       False       True     False   
4         24.59     4     False        True       False       True     False   
..          ...   ...       ...         ...         ...        ...       ...   
239       29.03     3      True       False       False       True     False   
240       27.18     2     False        True        True      False     False   
241       22.67     2      True       False        True      False     False   
242       17.82     2      True       False       False       True     False   
243       18.78     2     False        True       False       True      True   

     day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0      False    False     True       False         True  
1      False    False     True       False         True  
2      False    False     True       False         True  
3      False    False     True       False         True  
4      False    False     True       False         True  
..       ...      ...      ...         ...          ...  
239    False     True    False       False         True  
240    False     True    False       False         True  
241    False     True    False       False         True  
242    False     True    False       False         True  
243    False    False    False       False         True  

[244 rows x 12 columns]

In [20]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [21]:
# Split train test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [22]:
tips_model_kec = LinearRegression()

In [23]:
tips_model_kec.fit(X_test, y_test)

LinearRegression()

In [30]:
# Predict
new_data = pd.DataFrame({'total_bill':[20], 'size':[5], 'sex': 'Male', 'day':'Sun', 'time':'Dinner', 'smoker': 'No'})

In [31]:
new_data

total_bill  size   sex  day    time smoker
0          20     5  Male  Sun  Dinner     No

In [32]:
new_data=pd.get_dummies(new_data)

In [33]:
new_data

total_bill  size  sex_Male  day_Sun  time_Dinner  smoker_No
0          20     5      True     True         True       True

In [34]:
for cols in X_train.columns:
    if cols not in new_data.columns:
        new_data[cols]=0

In [35]:
new_data

total_bill  size  sex_Male  day_Sun  time_Dinner  smoker_No  sex_Female  \
0          20     5      True     True         True       True           0   

   smoker_Yes  day_Thur  day_Fri  day_Sat  time_Lunch  
0           0         0        0        0           0

In [36]:
new_data=new_data[X_train.columns]

In [38]:
new_data

total_bill  size  sex_Male  sex_Female  smoker_Yes  smoker_No  day_Thur  \
0          20     5      True           0           0       True         0   

   day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0        0        0     True           0         True

In [41]:
new_predict=tips_model_kec.predict(new_data)

In [42]:
new_predict

array([2.58066187])